### ISSUE TITLE
Tracis CI tests fail due to ROI dependencies in spaMM

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#166]
Seems that the latest 3.2.0 update in spaMM added a dependency on Rglpk, which breaks the Travis CI builds, and consequently causes various other packages that depend on DHARMa to fail, see 

* https://github.com/trotsiuk/r3PG/issues/26
* https://github.com/PecanProject/pecan/pull/2574

The error on DHARMa Travis CI is 

```
* installing *source* package ‘Rglpk’ ...
** package ‘Rglpk’ successfully unpacked and MD5 sums checked
** libs
/bin/bash: line 0: cd: GLPK: No such file or directory
Makevars:10: recipe for target 'GLPK.ts' failed
make: *** [GLPK.ts] Error 1
ERROR: compilation failed for package ‘Rglpk’
* removing ‘/home/travis/R/Library/Rglpk’
Error in i.p(...) : 
  (converted from warning) installation of package ‘Rglpk’ had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
Your build has been stopped.
```
Locally, I can install spaMM without problems. I'm not sure who's problem this is, it seems to me that it is actually a Travis problem.

**Comment by florianhartig** [comment]
OK, it seems that this can be fixed by adding 

      - glpk-utils
      - libglpk-dev

to the addons in the Travis yml file, as in 

```
# Install nlopt package to help nloptr install.
addons:
  apt:
    packages:
      - libnlopt-dev
      - glpk-utils
      - libglpk-dev
```

 - libnlopt-dev is optional, but usually needed for some other things, so I would include the entire block.

**Comment by florianhartig** [comment]
Based on https://github.com/PecanProject/pecan/pull/2574#issuecomment-616699816 it seems that just libglpk-dev is also sufficient

```
# Install nlopt package to help nloptr install
# libglpk-dev is needed because of DHARMa #166
addons:
  apt:
    packages:
      - libnlopt-dev
      - libglpk-dev
```
